language: node_js
node_js:
  - node
  - lts/*
install:
  - npm install
script:
  # - npm run lint:styles
  # - npm run lint:js
  # - npm run lint:html
  - npm run build
deploy:
  # clear bucket before deploy?
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "www.thegoldenhack.ca"
  skip_cleanup: true
  region: "us-east-2"
  on:
    branch: master
    node: 'lts/*'
